// Global settings
:ascii-ids:
:encoding: UTF-8
:lang: pt_PT
:icons: font
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:stem:

ifdef::env-github[]
:imagesdir: images/
endif::[]

[[doc]]
= SGFP - Implementação
:author: SGPF Team
:revnumber: 
:revdate: {docdatetime}
:version-label!:

NOTE: Edited: 2020-01-12. Generated: {localdate} {localtime}

toc::[]

[[doc.summary]]
== Summary

Este documento apresenta detalhes de implementação do SGPF



== Framework

* CDI (Alternative Spring)
* DeltaSkipe 
** CDI
* JPA (implentação: Hibernate, EclipseLink)
** Entidade, Associações de base de dados
* Vaadin Flow

== Infraestrtura de acesso a dados 


JPA - Definição script criação schemas (documentos, auth, )

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/create-schema.sql

JPA - Definição dados iniciais

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/initial-data.sql


Datasource - Base de dados HSQL (javax.Datasource)

* JdbcUrl jdbc:hsqldb:file:~/.sgpf/sgpf_database
* UserName sa
* Password sa

== JPA - Estrategias de Herança

A herança de classes não é possivel em base de dados relacional, logo é necessario definir uma estrategia para a implementação do conceito de herança. "fisica/tabelas"

JPA

* Single table Inheritance - InheritanceType.SINGLE_TABLE
* Table per class - InheritanceType.TABLE_PER_CLASS
* Joined multi table -  InheritanceType.JOINED


----
@DiscriminatorColumn 
@DiscriminatorValue 
----

Neste caso usamos "manualmente" 


== Dados 


Documento 

Documentos no sistema

* Despacho de abertura (DespachoAberturaDoc)


O Ato Administrativo: 

* Validade e eficácia; Extinção do ato
* Revogação

[plantuml]
----
class Historico


package "Documentos" #DDDDDD {

interface Documento 

class DespachoAberturaDoc

abstract class DespachoFinanciamento

class DespachoFinanciamentoIncentivo

class DespachoFinanciamentoBonificacao

class Candidatura

}

class Projeto

#1168bd
class EstadoCorrente {

    Projeto: Integer 
    Entidade: String
    EntidadeId: String 
    
}


Documento <|-- DespachoAberturaDoc


Documento <|-- DespachoFinanciamento

----

== Definições Gerais 

Bonificação::

Os apoios financeiros do Estado, concedidos pela DGTF sob a forma de bonificação de juros de operações financiadas pelas Instituições de Crédito, têm diferentes destinatários e são normalmente concedidas no âmbito de Linhas de Crédito.
Bonificação de taxa de juro

== Reference

* Inheritance strategies with JPA and Hibernate

