////
 *******************************************************************************
 * Copyright 2020 Paulo Borges(poolborges)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************
////
// Global settings
:ascii-ids:
:encoding: UTF-8
:lang: pt_PT
:icons: font
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:stem:

ifdef::env-github[]
:imagesdir: images/
endif::[]

[[doc]]
= Implementação
:author: SGPF Team
:revnumber: 
:revdate: {docdatetime}
:version-label!:

NOTE: Edited: 2020-01-12. Generated: {localdate} {localtime}

toc::[]

[[doc.summary]]
== Summary

Este documento apresenta detalhes de implementação do SGPF



== Framework

* CDI (Alternative Spring)
* DeltaSkipe 
** CDI
* JPA (implentação: Hibernate, EclipseLink)
** Entidade, Associações de base de dados
* Vaadin Flow

== Infraestrtura de acesso a dados 


JPA - Definição script criação schemas (documentos, auth, )

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/create-schema.sql

JPA - Definição dados iniciais

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/initial-data.sql


Datasource - Base de dados HSQL (javax.Datasource)

* JdbcUrl jdbc:hsqldb:file:~/.sgpf/sgpf_database
* UserName sa
* Password sa

== JPA - Estrategias de Herança

A herança de classes não é possivel em base de dados relacional, logo é necessario definir uma estrategia para a implementação do conceito de herança. "fisica/tabelas"

JPA

* Single table Inheritance - InheritanceType.SINGLE_TABLE
* Table per class - InheritanceType.TABLE_PER_CLASS
* Joined multi table -  InheritanceType.JOINED


----
@DiscriminatorColumn 
@DiscriminatorValue 
----

Neste caso usamos "manualmente" 


== Dados 


Documentos no sistema

* Despacho de abertura (DespachoAberturaDoc)


O Ato Administrativo: 

* Validade e eficácia; Extinção do ato
* Revogação

[plantuml]
----
package "Documentos" #DDDDDD {

interface Documento 

class DespachoAberturaDoc

abstract class DespachoFinanciamento

class DespachoFinanciamentoIncentivo

class DespachoFinanciamentoBonificacao

class Candidatura

}

package "Projeto" #DDDCCC {

class Projeto
class EstadoCorrente
class Historico

}


class EstadoCorrente {

    Projeto: Integer 
    Entidade: String
    EntidadeId: String 
}

Documento <|-- DespachoAberturaDoc
Documento <|-- DespachoFinanciamento
----

== Definições Gerais 

Bonificação::

Os apoios financeiros do Estado, concedidos pela DGTF sob a forma de bonificação de juros de operações financiadas pelas Instituições de Crédito, têm diferentes destinatários e são normalmente concedidas no âmbito de Linhas de Crédito.
Bonificação de taxa de juro


== Vaadin (DEV)

For documentation on using Vaadin Flow and CDI, 
visit [vaadin.com/docs](https://vaadin.com/docs/v14/flow/cdi/tutorial-cdi-basic.html)

For more information on Vaadin Flow, visit https://vaadin.com/flow.

Vaadin Flow Scoped

* @VaadinSessionScoped 
* @RouteScoped

Vaadin Framework

* @ViewScoped

CDI Scoped

* javax.enterprise.context
* @Dependent - is a "pseudo-scoped", what means: 


Vaadin Form binding 

Documentation fo Vaddin 8 to understand Binder (Is not vaadin-flow)

* https://vaadin.com/blog/vaadin-8-binder
* https://vaadin.com/docs/v8/framework/datamodel/datamodel-forms.html


== Reference

* Inheritance strategies with JPA and Hibernate

