= Implementação
:navtitle: Implementação
:author: SGPF Team
:revnumber: 2020-12-18
:revdate: {docdatetime}
:version-label!:
:edited: 2020-12-18
:generated: {localdate} {localtime}

[[doc.summary]]
== Summary

Este documento apresenta detalhes de implementação do SGPF



== Framework

* CDI (Alternative Spring)
* DeltaSkipe 
** CDI
* JPA (implentação: Hibernate, EclipseLink)
** Entidade, Associações de base de dados
* Vaadin Flow

== Infraestrtura de acesso a dados 


JPA - Definição script criação schemas (documentos, auth, )

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/create-schema.sql

JPA - Definição dados iniciais

* {SGPF_SOURCE}/src/main/resources/META-INF/sql/initial-data.sql


Datasource - Base de dados HSQL (javax.Datasource)

* JdbcUrl jdbc:hsqldb:file:~/.sgpf/sgpf_database
* UserName sa
* Password sa

== JPA - Estrategias de Herança

A herança de classes não é possivel em base de dados relacional, logo é necessario definir uma estrategia para a implementação do conceito de herança. "fisica/tabelas"

JPA

* Single table Inheritance - InheritanceType.SINGLE_TABLE
* Table per class - InheritanceType.TABLE_PER_CLASS
* Joined multi table -  InheritanceType.JOINED


----
@DiscriminatorColumn 
@DiscriminatorValue 
----

Neste caso usamos "manualmente" 


== Dados 


Documentos no sistema

* Despacho de abertura (DespachoAberturaDoc)


O Ato Administrativo: 

* Validade e eficácia; Extinção do ato
* Revogação

[plantuml]
----
package "Documentos" #DDDDDD {

interface Documento 

class DespachoAberturaDoc

abstract class DespachoFinanciamento

class DespachoFinanciamentoIncentivo

class DespachoFinanciamentoBonificacao

class Candidatura

}

package "Projeto" #DDDCCC {

class Projeto
class EstadoCorrente
class Historico

}


class EstadoCorrente {

    Projeto: Integer 
    Entidade: String
    EntidadeId: String 
}

Documento <|-- DespachoAberturaDoc
Documento <|-- DespachoFinanciamento
----

== Definições Gerais 

Bonificação::

Os apoios financeiros do Estado, concedidos pela DGTF sob a forma de bonificação de juros de operações financiadas pelas Instituições de Crédito, têm diferentes destinatários e são normalmente concedidas no âmbito de Linhas de Crédito.
Bonificação de taxa de juro


== Vaadin (DEV)

For documentation on using Vaadin Flow and CDI, 
visit [vaadin.com/docs](https://vaadin.com/docs/v14/flow/cdi/tutorial-cdi-basic.html)

For more information on Vaadin Flow, visit https://vaadin.com/flow.

Vaadin Flow Scoped

* @VaadinSessionScoped 
* @RouteScoped

Vaadin Framework

* @ViewScoped

CDI Scoped

* javax.enterprise.context
* @Dependent - is a "pseudo-scoped", what means: 


Vaadin Form binding 

Documentation fo Vaddin 8 to understand Binder (Is not vaadin-flow)

* https://vaadin.com/blog/vaadin-8-binder
* https://vaadin.com/docs/v8/framework/datamodel/datamodel-forms.html


== Reference

* Inheritance strategies with JPA and Hibernate

